env:
  commonjs: true
  es2021: true
  node: true
  mocha: true
  browser: true
  jest: true
  cypress: true
extends:
  - eslint:recommended
  # - google
plugins:
  - prettier
parserOptions:
    ecmaVersion: 12
    sourceType: 'module'
rules: { 'prettier/prettier': 'error' }
